#!/usr/bin/env python3
"""
Odoo ACL Verification Script
=============================

This script verifies that a user has read-only access to Odoo models.
It tests actual permissions via XML-RPC to confirm the ACL setup worked.

Usage:
    # Verify with default target user from .env
    python verify_readonly_acl.py

    # Verify a specific user
    python verify_readonly_acl.py --user accounting@qagroup.com.au

    # Test specific models
    python verify_readonly_acl.py --models res.partner,crm.lead,project.project

    # Output as JSON
    python verify_readonly_acl.py --json

Requirements:
    pip install python-dotenv colorama tabulate

Author: Generated by Claude Code
"""

import os
import sys
import json
import argparse
from pathlib import Path
from typing import Dict, List, Any, Optional
import xmlrpc.client

# Optional dependencies with graceful fallback
try:
    from dotenv import load_dotenv
    HAS_DOTENV = True
except ImportError:
    HAS_DOTENV = False

try:
    from colorama import init, Fore, Style
    init()
    HAS_COLORAMA = True
except ImportError:
    HAS_COLORAMA = False
    class Fore:
        RED = GREEN = YELLOW = CYAN = MAGENTA = WHITE = RESET = ""
    class Style:
        BRIGHT = RESET_ALL = ""

try:
    from tabulate import tabulate
    HAS_TABULATE = True
except ImportError:
    HAS_TABULATE = False


# Default models to test (cover common areas)
DEFAULT_TEST_MODELS = [
    'res.partner',           # Contacts
    'res.users',             # Users
    'crm.lead',              # CRM Leads
    'sale.order',            # Sales Orders
    'purchase.order',        # Purchase Orders
    'account.move',          # Invoices/Bills
    'account.move.line',     # Journal Items
    'project.project',       # Projects
    'project.task',          # Tasks
    'stock.picking',         # Inventory Transfers
    'product.product',       # Products
    'product.template',      # Product Templates
    'hr.employee',           # Employees
    'mail.message',          # Messages
]


class Config:
    """Configuration loaded from environment variables or .env file."""

    def __init__(self):
        if HAS_DOTENV:
            env_path = Path(__file__).parent / '.env'
            if env_path.exists():
                load_dotenv(env_path)

        self.url = os.getenv('ODOO_URL', '')
        self.db = os.getenv('ODOO_DB', '')
        self.target_user_login = os.getenv('TARGET_USER_LOGIN', '')
        # For verification, we need the target user's credentials
        self.target_user_password = os.getenv('TARGET_USER_PASSWORD', '')

    def validate(self) -> List[str]:
        errors = []
        if not self.url:
            errors.append("ODOO_URL is required")
        if not self.db:
            errors.append("ODOO_DB is required")
        if not self.target_user_login:
            errors.append("TARGET_USER_LOGIN is required")
        if not self.target_user_password:
            errors.append("TARGET_USER_PASSWORD is required for verification")
        return errors


class PermissionVerifier:
    """Verifies Odoo permissions via XML-RPC."""

    def __init__(self, config: Config):
        self.config = config
        self.uid: Optional[int] = None
        self.common: Optional[xmlrpc.client.ServerProxy] = None
        self.models: Optional[xmlrpc.client.ServerProxy] = None

    def connect(self) -> bool:
        """Authenticate with Odoo as the target user."""
        try:
            self.common = xmlrpc.client.ServerProxy(
                f'{self.config.url}/xmlrpc/2/common',
                allow_none=True
            )
            self.models = xmlrpc.client.ServerProxy(
                f'{self.config.url}/xmlrpc/2/object',
                allow_none=True
            )

            self.uid = self.common.authenticate(
                self.config.db,
                self.config.target_user_login,
                self.config.target_user_password,
                {}
            )

            if not self.uid:
                print(f"{Fore.RED}Authentication failed for {self.config.target_user_login}{Style.RESET_ALL}")
                return False

            print(f"{Fore.GREEN}Connected as {self.config.target_user_login} (UID: {self.uid}){Style.RESET_ALL}")
            return True

        except Exception as e:
            print(f"{Fore.RED}Connection error: {e}{Style.RESET_ALL}")
            return False

    def check_model_access(self, model_name: str) -> Dict[str, Any]:
        """Check all permission types for a model."""
        result = {
            'model': model_name,
            'exists': False,
            'read': False,
            'write': False,
            'create': False,
            'unlink': False,
            'error': None
        }

        try:
            # First check if model exists
            model_ids = self.models.execute_kw(
                self.config.db, self.uid, self.config.target_user_password,
                'ir.model', 'search',
                [[('model', '=', model_name)]],
                {'limit': 1}
            )

            if not model_ids:
                result['error'] = 'Model not found'
                return result

            result['exists'] = True

            # Check each permission type
            for operation in ['read', 'write', 'create', 'unlink']:
                try:
                    has_access = self.models.execute_kw(
                        self.config.db, self.uid, self.config.target_user_password,
                        model_name, 'check_access_rights',
                        [operation],
                        {'raise_exception': False}
                    )
                    result[operation] = bool(has_access)
                except Exception:
                    result[operation] = False

        except Exception as e:
            result['error'] = str(e)

        return result

    def test_actual_operations(self, model_name: str) -> Dict[str, Any]:
        """Test actual CRUD operations on a model."""
        result = {
            'model': model_name,
            'can_search': False,
            'can_read': False,
            'can_create': False,
            'can_write': False,
            'can_unlink': False,
            'errors': {}
        }

        try:
            # Test search
            record_ids = self.models.execute_kw(
                self.config.db, self.uid, self.config.target_user_password,
                model_name, 'search',
                [[]],
                {'limit': 1}
            )
            result['can_search'] = True

            # Test read (if we have records)
            if record_ids:
                records = self.models.execute_kw(
                    self.config.db, self.uid, self.config.target_user_password,
                    model_name, 'read',
                    [record_ids],
                    {'fields': ['id']}
                )
                result['can_read'] = len(records) > 0

        except Exception as e:
            result['errors']['search_read'] = str(e)

        # Test create (we expect this to fail for read-only users)
        try:
            # Try to create with minimal data - this should fail
            self.models.execute_kw(
                self.config.db, self.uid, self.config.target_user_password,
                model_name, 'create',
                [{'name': '__acl_test_record__'}]
            )
            result['can_create'] = True
            result['errors']['create'] = 'WARNING: Create succeeded - user is NOT read-only!'
        except xmlrpc.client.Fault as e:
            if 'access' in str(e).lower() or 'permission' in str(e).lower():
                result['can_create'] = False  # Expected behavior
            else:
                result['errors']['create'] = str(e)

        return result


def format_permission(has_access: bool) -> str:
    """Format permission as colored string."""
    if has_access:
        return f"{Fore.GREEN}YES{Style.RESET_ALL}"
    else:
        return f"{Fore.RED}NO{Style.RESET_ALL}"


def format_readonly_status(result: Dict[str, Any]) -> str:
    """Check if permissions match read-only pattern."""
    if result.get('error'):
        return f"{Fore.YELLOW}ERROR{Style.RESET_ALL}"

    is_readonly = (
        result.get('read', False) and
        not result.get('write', False) and
        not result.get('create', False) and
        not result.get('unlink', False)
    )

    if is_readonly:
        return f"{Fore.GREEN}READ-ONLY{Style.RESET_ALL}"
    elif not result.get('read', False):
        return f"{Fore.YELLOW}NO ACCESS{Style.RESET_ALL}"
    else:
        return f"{Fore.RED}HAS WRITE{Style.RESET_ALL}"


def main():
    parser = argparse.ArgumentParser(
        description='Verify Odoo ACL permissions for a user',
        formatter_class=argparse.RawDescriptionHelpFormatter
    )

    parser.add_argument('--user', type=str,
                        help='Target user login (overrides .env)')
    parser.add_argument('--password', type=str,
                        help='Target user password (overrides .env)')
    parser.add_argument('--models', type=str,
                        help='Comma-separated list of models to test')
    parser.add_argument('--all-models', action='store_true',
                        help='Test all accessible models (slow)')
    parser.add_argument('--json', action='store_true',
                        help='Output results as JSON')
    parser.add_argument('--test-operations', action='store_true',
                        help='Test actual CRUD operations (creates test records)')

    args = parser.parse_args()

    # Load configuration
    config = Config()

    # Override from command line
    if args.user:
        config.target_user_login = args.user
    if args.password:
        config.target_user_password = args.password

    # Validate
    errors = config.validate()
    if errors:
        print(f"{Fore.RED}Configuration errors:{Style.RESET_ALL}")
        for error in errors:
            print(f"  - {error}")
        print("\nPlease set TARGET_USER_PASSWORD in .env or use --password")
        sys.exit(1)

    # Print header
    print(f"\n{Fore.MAGENTA}{'='*60}{Style.RESET_ALL}")
    print(f"{Fore.MAGENTA}Odoo ACL Verification{Style.RESET_ALL}")
    print(f"{Fore.MAGENTA}{'='*60}{Style.RESET_ALL}")
    print(f"URL: {config.url}")
    print(f"Database: {config.db}")
    print(f"User: {config.target_user_login}")

    # Connect as target user
    verifier = PermissionVerifier(config)
    if not verifier.connect():
        sys.exit(1)

    # Determine which models to test
    if args.models:
        test_models = [m.strip() for m in args.models.split(',')]
    elif args.all_models:
        # Get all models
        print("\nFetching all models...")
        all_models = verifier.models.execute_kw(
            config.db, verifier.uid, config.target_user_password,
            'ir.model', 'search_read',
            [[('transient', '=', False)]],
            {'fields': ['model'], 'order': 'model'}
        )
        test_models = [m['model'] for m in all_models]
        print(f"Found {len(test_models)} models to test")
    else:
        test_models = DEFAULT_TEST_MODELS

    # Check permissions
    print(f"\n{Fore.CYAN}Checking permissions for {len(test_models)} models...{Style.RESET_ALL}\n")

    results = []
    for model_name in test_models:
        result = verifier.check_model_access(model_name)
        results.append(result)

    # Output results
    if args.json:
        print(json.dumps(results, indent=2))
    else:
        if HAS_TABULATE:
            headers = ['Model', 'Read', 'Write', 'Create', 'Delete', 'Status']
            rows = []
            for r in results:
                if r.get('error'):
                    rows.append([
                        r['model'],
                        '-', '-', '-', '-',
                        f"{Fore.YELLOW}{r['error']}{Style.RESET_ALL}"
                    ])
                else:
                    rows.append([
                        r['model'],
                        format_permission(r['read']),
                        format_permission(r['write']),
                        format_permission(r['create']),
                        format_permission(r['unlink']),
                        format_readonly_status(r)
                    ])
            print(tabulate(rows, headers=headers, tablefmt='grid'))
        else:
            # Simple format without tabulate
            print(f"{'Model':<40} {'Read':<6} {'Write':<6} {'Create':<6} {'Delete':<6} {'Status':<12}")
            print("-" * 90)
            for r in results:
                if r.get('error'):
                    print(f"{r['model']:<40} {'-':<6} {'-':<6} {'-':<6} {'-':<6} {r['error']}")
                else:
                    status = 'READ-ONLY' if (r['read'] and not r['write'] and not r['create'] and not r['unlink']) else 'HAS WRITE' if r['write'] or r['create'] or r['unlink'] else 'NO ACCESS'
                    print(f"{r['model']:<40} {'Y' if r['read'] else 'N':<6} {'Y' if r['write'] else 'N':<6} {'Y' if r['create'] else 'N':<6} {'Y' if r['unlink'] else 'N':<6} {status:<12}")

    # Summary
    readonly_count = sum(1 for r in results if r.get('read') and not r.get('write') and not r.get('create') and not r.get('unlink'))
    has_write_count = sum(1 for r in results if r.get('write') or r.get('create') or r.get('unlink'))
    no_access_count = sum(1 for r in results if not r.get('read') and not r.get('error'))
    error_count = sum(1 for r in results if r.get('error'))

    print(f"\n{Fore.CYAN}{'='*60}{Style.RESET_ALL}")
    print(f"{Fore.CYAN}SUMMARY{Style.RESET_ALL}")
    print(f"{Fore.CYAN}{'='*60}{Style.RESET_ALL}")
    print(f"Total models tested: {len(results)}")
    print(f"{Fore.GREEN}Read-only:          {readonly_count}{Style.RESET_ALL}")
    print(f"{Fore.RED}Has write access:   {has_write_count}{Style.RESET_ALL}")
    print(f"{Fore.YELLOW}No access:          {no_access_count}{Style.RESET_ALL}")
    print(f"Errors:             {error_count}")

    if has_write_count > 0:
        print(f"\n{Fore.RED}WARNING: User has write access to {has_write_count} models!{Style.RESET_ALL}")
        print("Models with write access:")
        for r in results:
            if r.get('write') or r.get('create') or r.get('unlink'):
                perms = []
                if r.get('write'): perms.append('write')
                if r.get('create'): perms.append('create')
                if r.get('unlink'): perms.append('delete')
                print(f"  - {r['model']}: {', '.join(perms)}")
        sys.exit(1)
    else:
        print(f"\n{Fore.GREEN}SUCCESS: User is read-only for all tested models!{Style.RESET_ALL}")
        sys.exit(0)


if __name__ == '__main__':
    main()
